# Pre-commit configuration for Python project
# This file configures hooks that run before each commit to ensure code quality

repos:
  # Standard Python hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        description: "Trim trailing whitespace"
      - id: end-of-file-fixer
        description: "Ensure files end with a newline"
      - id: check-yaml
        description: "Check YAML files for syntax errors"
      - id: check-added-large-files
        description: "Check for files over 500KB"
        args: ['--maxkb=500']
      - id: check-merge-conflict
        description: "Check for merge conflict markers"
      - id: debug-statements
        description: "Check for debugger imports"

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        description: "Format Python code with Black"
        language_version: python3
        args: [--line-length=88]

  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        description: "Sort Python imports"
        args: [--profile=black]

  # Python code linting (focused on src/ folder only)
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        description: "Lint Python code with flake8"
        args: [--max-line-length=88]
        # Only lint the main project, skip learning materials
        files: ^src/.*\.py$

# Configuration
default_stages: [pre-commit]
fail_fast: false
